/**
 * notes.js — shared "what is this?" annotations for StorageSaver.
 *
 * Four layers, first hit wins:
 *   1. node.note already set by the scanner's classify() (safety guidance)
 *   2. BUILTIN — hand-written notes for names every Mac/dev box has
 *   3. your local cache (~/.config/storagesaver/notes-cache.json) — notes
 *      generated by `storagesaver annotate` against YOUR LLM endpoint
 *   4. seed-notes.json — notes for common apps/dirs that ship with the repo
 * Cache entries the model marked UNSURE are skipped so a human (or a
 * smarter model) can fill them — never guessed.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const SEED_FILE = path.join(__dirname, 'seed-notes.json');

function configDir() {
  return process.env.STORAGESAVER_CONFIG_DIR ||
    path.join(process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config'), 'storagesaver');
}

const CACHE_FILE = () => path.join(configDir(), 'notes-cache.json');

// Generic names — same meaning wherever they appear.
const BUILTIN = {
  'node_modules': 'installed npm packages for a JS project — safe to delete, `npm install` restores them',
  '.git': 'the project\'s git version history — deleting breaks the repo link',
  'library': 'app settings, caches, and support data — macOS keeps per-app files here',
  'application support': 'per-app data files (settings, databases, downloads) — apps store their stuff here',
  'caches': 'temporary files apps rebuild on demand',
  'cache': 'temporary files the app rebuilds on demand',
  'containers': 'sandboxed apps\' private data folders',
  'group containers': 'data shared between an app and its extensions (e.g. Docker, iMessage apps)',
  'preferences': 'app settings files (.plist)',
  'logs': 'diagnostic log files — safe to clear, apps recreate them',
  'deriveddata': 'Xcode build output — regenerates on next build',
  'coresimulator': 'iOS simulator devices and their installed apps',
  'applications': 'installed apps',
  'downloads': 'your browser/app downloads',
  'desktop': 'files on your Desktop',
  'documents': 'your documents folder',
  'movies': 'your videos folder',
  'pictures': 'your photos and images folder',
  'music': 'your music folder',
  'photos library.photoslibrary': 'your Photos app library — manage inside Photos, never in Finder',
  'system': 'macOS itself — read-only system files',
  'private': 'macOS system data: temp files, logs, swap, databases',
  'var': 'system-managed data: logs, temp caches, swap',
  'folders': 'per-user temporary files and caches macOS manages automatically',
  'tmp': 'temporary files — cleared on reboot',
  'log': 'system log files',
  'usr': 'Unix tools and manually installed software',
  'opt': 'optional software — on Apple Silicon Macs this is mostly Homebrew',
  'homebrew': 'the Homebrew package manager and everything installed through it',
  'cellar': 'Homebrew\'s installed packages live here',
  'caskroom': 'Homebrew-installed GUI apps',
  '.npm': 'npm\'s download cache — regenerates',
  '.nvm': 'Node.js version manager — holds each installed Node version',
  '.cache': 'command-line tools\' caches (models, wheels, builds) — mostly regenerable',
  '.venv': 'a Python virtual environment — recreate with pip/uv',
  'venv': 'a Python virtual environment — recreate with pip/uv',
  'virtualenvs': 'Python virtual environments (one per project) — recreate with pip/pipenv',
  'site-packages': 'installed Python packages for one environment',
  '__pycache__': 'compiled Python bytecode — regenerates automatically',
  'dist': 'built/packaged output of a project — regenerates from source',
  'build': 'build output — regenerates from source',
  '.trash': 'your Trash — empty it from Finder',
  'mobilesync': 'iPhone/iPad backups made by Finder',
  'cloudstorage': 'cloud drives (Google Drive, Dropbox) — deleting here deletes in the cloud',
  'mobile documents': 'iCloud Drive — deleting here deletes from iCloud everywhere',
  'messages': 'your iMessage history and attachments',
  'mail': 'your Mail.app messages and attachments',
  'saved application state': 'window positions apps restore on relaunch — tiny and harmless',
  'launchagents': 'programs configured to auto-start when you log in',
  'frameworks': 'shared code libraries apps depend on',
  'extensions': 'app/browser extensions',
  'plug-ins': 'app plug-ins',
  'resources': 'an app\'s bundled images, sounds, and data files',
  'contents': 'the inside of a macOS app bundle',
  'macos': 'the app\'s actual executable program',
  'assetsv2': 'macOS staged system-update files — managed by macOS',
  'dyld': 'macOS prebuilt app-launch caches — system managed',
};

// Machine-generated names (hashes, UUIDs, versions, store IDs) — pointless to
// ask an LLM about; they get a derived note instead and are skipped as work.
const OPAQUE = [
  /^[0-9a-f]{16,}$/i,                                              // hex hash
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, // UUID
  /^v?\d+(\.\d+)+(_\d+)?$/,                                        // version dir
  /^[a-p]{32}$/,                                                   // Chrome extension ID
  /^\d{10}(\.\d+)?$/,                                              // epoch timestamp
  /^\d+$/,                                                         // bare numeric dir
  /^[0-9a-f]{2}$/i,                                                // 2-hex shard dir
  /^[a-z]$/i,                                                      // single-letter shard (var/folders C/T/X)
];
function isOpaque(name) { return OPAQUE.some(re => re.test(name)); }
function opaqueNote(node) {
  if (/\/Extensions\//.test(node.p)) return 'a Chrome extension (machine ID) — match it at chrome://extensions';
  if (/^v?\d+(\.\d+)+(_\d+)?$/.test(node.n)) return 'one installed version of the tool named by its parent folder';
  return 'machine-named internal data — judge it by its parent folder';
}

function loadSeed() {
  try { return JSON.parse(fs.readFileSync(SEED_FILE, 'utf8')).notes || {}; }
  catch (_) { return {}; }
}

// Load the user's local cache, seeded with the shipped notes. Cache entries
// (your own annotations) override the seed.
function loadCache() {
  let cache = { notes: {}, unsure: [] };
  try { cache = JSON.parse(fs.readFileSync(CACHE_FILE(), 'utf8')); }
  catch (_) { /* first run */ }
  if (!cache.notes) cache.notes = {};
  if (!Array.isArray(cache.unsure)) cache.unsure = [];
  cache.notes = Object.assign({}, loadSeed(), cache.notes);
  return cache;
}

// Persist only the user's own annotations (not the shipped seed).
function saveCache(cache) {
  const seed = loadSeed();
  const own = {};
  for (const [k, v] of Object.entries(cache.notes || {})) {
    if (seed[k] !== v) own[k] = v;
  }
  fs.mkdirSync(configDir(), { recursive: true });
  fs.writeFileSync(CACHE_FILE(), JSON.stringify({ notes: own, unsure: cache.unsure || [] }, null, 2));
}

// Fill node.note in place (recursively) from BUILTIN + cache. Existing notes win.
function applyNotes(root, cache) {
  const notes = (cache && cache.notes) || {};
  (function walk(x) {
    if (!x.note && !x.n.startsWith('(other')) {
      const key = x.n.toLowerCase();
      x.note = BUILTIN[key] || notes[key] || (isOpaque(x.n) ? opaqueNote(x) : null);
    }
    (x.c || []).forEach(walk);
  })(root);
}

module.exports = { BUILTIN, CACHE_FILE, SEED_FILE, configDir, loadSeed, loadCache, saveCache, applyNotes, isOpaque };
